version: '3'

services:
  proxy:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: proxy
    container_name: nodejs
    restart: unless-stopped
    env_file: ./src/.env
    ports:
      - "8213:8213"
    volumes:
      - ./src:/home/node/app
      - ./src/node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/nodemon app.js

networks:
  app-network:
    driver: bridge