version: '3'

services:
  router:
    build:
      context: ./apps/oauth2-router
    image: oauth2-router
    command: npm run dev
    container_name: router
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./apps/oauth2-router:/home/node/app
      - ./apps/oauth2-router/node_modules:/home/node/app/node_modules

  # The client app is a placeholder which simulates a web app launched in an
  # ephemeral Release environment. This should be replaced with your real client
  # app.
  client:
    build:
      context: ./apps/oauth2-client
    image: oauth2-client
    command: npm run dev
    container_name: client
    restart: unless-stopped
    env_file: ./apps/oauth2-client/.env
    ports:
      - "8080:8080"
